// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: polycommit.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Pk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	G1P [][]byte `protobuf:"bytes,1,rep,name=g1_p,json=g1P,proto3" json:"g1_p,omitempty"`
	G2P [][]byte `protobuf:"bytes,2,rep,name=g2_p,json=g2P,proto3" json:"g2_p,omitempty"`
}

func (x *Pk) Reset() {
	*x = Pk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polycommit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pk) ProtoMessage() {}

func (x *Pk) ProtoReflect() protoreflect.Message {
	mi := &file_polycommit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pk.ProtoReflect.Descriptor instead.
func (*Pk) Descriptor() ([]byte, []int) {
	return file_polycommit_proto_rawDescGZIP(), []int{0}
}

func (x *Pk) GetG1P() [][]byte {
	if x != nil {
		return x.G1P
	}
	return nil
}

func (x *Pk) GetG2P() [][]byte {
	if x != nil {
		return x.G2P
	}
	return nil
}

var File_polycommit_proto protoreflect.FileDescriptor

var file_polycommit_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x6f, 0x6c, 0x79, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x02, 0x50, 0x6b, 0x12,
	0x11, 0x0a, 0x04, 0x67, 0x31, 0x5f, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x03, 0x67,
	0x31, 0x50, 0x12, 0x11, 0x0a, 0x04, 0x67, 0x32, 0x5f, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x03, 0x67, 0x32, 0x50, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x74, 0x6c, 0x75, 0x6f, 0x2f, 0x6c, 0x69, 0x62, 0x70, 0x6f,
	0x6c, 0x79, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_polycommit_proto_rawDescOnce sync.Once
	file_polycommit_proto_rawDescData = file_polycommit_proto_rawDesc
)

func file_polycommit_proto_rawDescGZIP() []byte {
	file_polycommit_proto_rawDescOnce.Do(func() {
		file_polycommit_proto_rawDescData = protoimpl.X.CompressGZIP(file_polycommit_proto_rawDescData)
	})
	return file_polycommit_proto_rawDescData
}

var file_polycommit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_polycommit_proto_goTypes = []interface{}{
	(*Pk)(nil), // 0: proto.Pk
}
var file_polycommit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_polycommit_proto_init() }
func file_polycommit_proto_init() {
	if File_polycommit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_polycommit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_polycommit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polycommit_proto_goTypes,
		DependencyIndexes: file_polycommit_proto_depIdxs,
		MessageInfos:      file_polycommit_proto_msgTypes,
	}.Build()
	File_polycommit_proto = out.File
	file_polycommit_proto_rawDesc = nil
	file_polycommit_proto_goTypes = nil
	file_polycommit_proto_depIdxs = nil
}
